# Generated by Django 4.2.30 on 2026-04-29 06:42

import config.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalnote',
            name='note',
            field=config.encryption.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='description',
            field=config.encryption.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis',
            field=config.encryption.EncryptedCharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=config.encryption.EncryptedCharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='instructions',
            field=config.encryption.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medication',
            field=config.encryption.EncryptedCharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='notes',
            field=config.encryption.EncryptedTextField(blank=True),
        ),
    ]
