# Generated by Django 4.2.30 on 2026-04-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_alter_clinicalnote_note_alter_diagnosis_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalnote',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='final', max_length=20),
        ),
    ]
