# Generated by Django 4.2.30 on 2026-04-29 12:47

import config.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_locked_user_mfa_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='details',
            field=config.encryption.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=config.encryption.EncryptedCharField(blank=True, max_length=500),
        ),
    ]
