# Generated by Django 4.2.30 on 2026-05-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_status_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_exempt',
            field=models.BooleanField(default=False),
        ),
    ]
