# Generated by Django 4.2.30 on 2026-05-12 20:55

import config.encryption
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='needs_password_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='temp_password',
            field=config.encryption.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
    ]
