# Generated by Django 4.2.30 on 2026-04-29 12:47

import config.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=config.encryption.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=config.encryption.EncryptedTextField(),
        ),
    ]
