# Generated by Django 4.2.30 on 2026-04-29 06:42

import config.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=config.encryption.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=config.encryption.EncryptedCharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_name',
            field=config.encryption.EncryptedCharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_phone',
            field=config.encryption.EncryptedCharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=config.encryption.EncryptedCharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=config.encryption.EncryptedCharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=config.encryption.EncryptedCharField(max_length=500),
        ),
    ]
